### ISSUE TITLE
Question on the meaning of the result.

### ISSUE THREAD

**Issue by chenkang455** [zwx8981/LIQE#18]
Hi, thanks for your great work. 
I am currently working on low-level vision and trying to utilize LIQE for testing the quantitative performance the restored image. I use the following code: 
```
metric = pyiqa.create_metric('liqe',as_loss=False).cuda() 
tensor([1.0016], device='cuda:0')
```
I am a little bit confused about this result, can you be kindly explain the meanning of this result like PSNR or SSIM ? (its range and higher better or lower better)

**Comment by zwx8981** [comment]
Thanks for your interest ! The higher LIQE output the better. It ranges in 1 to 5

**Comment by chenkang455** [comment]
> Thanks for your interest ! The higher LIQE output the better. It ranges in 1 to 5

thanks for your response. I find that my result ranges from 1 to 1.01, is that normal?

**Comment by zwx8981** [comment]
@chenkang455 Not that normal. Can you send me some images with both low and high quality in your case? I will see what's the problem.

**Comment by chenkang455** [comment]
@zwx8981 , hi these are my test images.
![Blur](https://github.com/zwx8981/LIQE/assets/72788314/d601cc2e-3891-4fd2-bd8d-8cb5cdc1bb21)
![deblur](https://github.com/zwx8981/LIQE/assets/72788314/68036193-bf8a-484c-8a65-2e5f3bcb5600)

**Comment by zwx8981** [comment]
@Thanks for your sharing ! Let me explain it step by step.

1, Although it is clear that the bottom image is of higher quality than the top one in your case, neither images are with high quality in a general context of "image quality". Even the bottom image is somewhat blurred.
2, I would suggest using liqe_mix instead of liqe by pyiqa.create_metric('liqe_mix', as_loss=False), which is trained on multiple image quality assessment datasets, leading to better quality prediction accuracy.
3, One last important thing, the resolution of these two images are quite different from the images used to train LIQE. I would suggest resize the image (keep aspect ratio) such that the short edge is 384. 

Combing the practices of 2 and 3, liqe_mix would give about 1 to the top image and 2.4 to the bottom image.

Best

**Comment by chenkang455** [comment]
> @chenkang455 Thanks for your sharing ! Let me explain it step by step.
> 
> 1, Although it is clear that the bottom image is of higher quality than the top one in your case, neither images are with high quality in a general context of "image quality". Even the bottom image is somewhat blurred. 2, I would suggest using liqe_mix instead of liqe by pyiqa.create_metric('liqe_mix', as_loss=False), which is trained on multiple image quality assessment datasets, leading to better quality prediction accuracy. 3, One last important thing, the resolution of these two images are quite different from the images used to train LIQE. I would suggest resize the image (keep aspect ratio) such that the short edge is 384.
> 
> Combing the practices of 2 and 3, liqe_mix would give about 1 to the top image and 2.4 to the bottom image.
> 
> Best

I have solved this problem. Thanks for your advice and your work is solid indeed！

**Comment by zwx8981** [comment]
Good to know that !

**Comment by chenkang455** [comment]
Just follow the steps explained by authors.
